/**
 * Recorded motion a sensor card can replay into the guest, one set per sample
 * that asks for it (`GuestSample.recordings` in src/boards.ts). A set names
 * the part it drives; its clips are x/y/z in g, one sample per guest fetch.
 *
 * magicWand.json is generated by tools/extract-magic-wand-gestures.py, which
 * checks every clip against the Magic Wand model before keeping it. See the
 * README beside this file for where the recordings come from.
 */

import magicWandJson from './magicWand.json'

export type Vec3 = readonly [number, number, number]

export interface RecordingClip {
  id: string
  label: string
  samples: readonly Vec3[]
}

export interface RecordingSet {
  /** `shellLabel` of the part the clips drive. */
  target: string
  /** Samples per second, for playback when no guest is reading. */
  rateHz: number
  /** The card's resting pose. Every clip starts and ends here. */
  rest: Vec3
  /** One line under the buttons: what the guest does with a clip. */
  hint: string
  credit: string
  source: string
  clips: readonly RecordingClip[]
}

export type RecordingSetId = 'magic-wand'

function asVec3(values: readonly number[]): Vec3 {
  return [values[0] ?? 0, values[1] ?? 0, values[2] ?? 0]
}

export const RECORDING_SETS: Record<RecordingSetId, RecordingSet> = {
  'magic-wand': {
    target: 'adxl345',
    rateHz: magicWandJson.rateHz,
    rest: asVec3(magicWandJson.rest),
    hint: 'The guest prints WING, RING or SLOPE in the terminal.',
    credit: magicWandJson.credit,
    source: magicWandJson.source,
    clips: magicWandJson.clips.map((clip) => ({
      id: clip.id,
      label: clip.label,
      samples: clip.samples.map(asVec3),
    })),
  },
}
