/**
 * GENERATED by scripts/gen-changelog.mjs from CHANGELOG.md. Do not edit by
 * hand — edit CHANGELOG.md and re-run the script.
 */

export interface ChangelogItem {
  tag: string
  text: string
}

export interface ChangelogRelease {
  version: string
  date: string | null
  items: ChangelogItem[]
}

export const CHANGELOG: ChangelogRelease[] = [
  {
    "version": "Unreleased",
    "date": null,
    "items": [
      {
        "tag": "Added",
        "text": "In-app changelog tab in the keyboard help dialog."
      },
      {
        "tag": "Added",
        "text": "One-shot semver release workflow for cutting app tags."
      },
      {
        "tag": "Added",
        "text": "Live board GDB attach card in the Debug panel."
      },
      {
        "tag": "Added",
        "text": "Session mode switch between Sim and Live board."
      },
      {
        "tag": "Added",
        "text": "CPU power states in Trace Timeline and Power tab."
      },
      {
        "tag": "Improved",
        "text": "Desktop bridge routes GDB frames to the owning client."
      }
    ]
  },
  {
    "version": "0.5.0",
    "date": "2026-07-30",
    "items": [
      {
        "tag": "Added",
        "text": "Desktop bridge for real network and Live board tracing."
      },
      {
        "tag": "Added",
        "text": "Settings menu for bridge URL and network uplink."
      },
      {
        "tag": "Added",
        "text": "Live board home surface when tracing a physical board."
      },
      {
        "tag": "Added",
        "text": "Probe daemon for serial CTF into Trace."
      },
      {
        "tag": "Changed",
        "text": "Bridge network is Settings-only (no separate gateway UI)."
      },
      {
        "tag": "Improved",
        "text": "Network uplink copy and port-forward recipe."
      }
    ]
  },
  {
    "version": "0.4.0",
    "date": "2026-07-28",
    "items": [
      {
        "tag": "Added",
        "text": "In-browser Bluetooth with Bumble HCI and controllable peers."
      },
      {
        "tag": "Added",
        "text": "Classic A2DP speaker peer with SBC decode."
      },
      {
        "tag": "Added",
        "text": "Virtio-blk FAT disk with a dock browser."
      },
      {
        "tag": "Added",
        "text": "Guided tours driven by the debugger, shipped with the page."
      },
      {
        "tag": "Added",
        "text": "Global keyboard shortcuts and ? help dialog."
      },
      {
        "tag": "Added",
        "text": "MCP2515 CAN on virtio-SPI."
      },
      {
        "tag": "Improved",
        "text": "Floating panels resize from any edge."
      }
    ]
  },
  {
    "version": "0.3.0",
    "date": "2026-07-26",
    "items": [
      {
        "tag": "Added",
        "text": "Trace panel with timeline, threads, and queues."
      },
      {
        "tag": "Added",
        "text": "GDB stub path with Step, breakpoints, and memory UI."
      },
      {
        "tag": "Added",
        "text": "Browser-backed QEMU monitor to pause the guest."
      },
      {
        "tag": "Added",
        "text": "Part identity catalog with datasheet links."
      },
      {
        "tag": "Added",
        "text": "GPIO 7-segment and PT6314 VFD aux displays."
      },
      {
        "tag": "Added",
        "text": "LP5012 RGB LED and SCT2024 SPI LED bar."
      },
      {
        "tag": "Improved",
        "text": "Flash and EEPROM stats with wear maps."
      }
    ]
  },
  {
    "version": "0.2.0",
    "date": "2026-07-24",
    "items": [
      {
        "tag": "Added",
        "text": "Device dock with sensors, GPIO, LEDs, and displays."
      },
      {
        "tag": "Added",
        "text": "I²C and SPI bus views with attach/detach and hex dumps."
      },
      {
        "tag": "Added",
        "text": "Ethernet panel with throughput charts and capture."
      },
      {
        "tag": "Added",
        "text": "GNSS, RTC, fuel gauge, DAC, PWM, and stepper rows."
      },
      {
        "tag": "Added",
        "text": "Sample gallery with board and app pickers."
      },
      {
        "tag": "Added",
        "text": "Drop an ELF onto the window to boot a custom image."
      }
    ]
  },
  {
    "version": "0.1.0",
    "date": "2026-07-22",
    "items": [
      {
        "tag": "Added",
        "text": "Initial release. Zephyr in a browser tab via qemu-wasm."
      },
      {
        "tag": "Added",
        "text": "Mock backend so the UI runs without an emulator build."
      },
      {
        "tag": "Added",
        "text": "Terminal chrome, board picker, and GitHub Pages deploy."
      }
    ]
  }
]
