/**
 * GENERATED by scripts/gen-changelog.mjs from CHANGELOG.md. Do not edit by
 * hand — edit CHANGELOG.md and re-run the script.
 */

export interface ChangelogItem {
  tag: string
  text: string
}

export interface ChangelogRelease {
  version: string
  date: string | null
  items: ChangelogItem[]
}

export const CHANGELOG: ChangelogRelease[] = [
  {
    "version": "Unreleased",
    "date": null,
    "items": [
      {
        "tag": "Added",
        "text": "Trace recording with slowed-down replay and a scrubber."
      },
      {
        "tag": "Added",
        "text": "Kite Rush sample: a mouse-flown arcade game that saves high scores."
      },
      {
        "tag": "Added",
        "text": "ZMS sample, and a flash view of its keys and history."
      },
      {
        "tag": "Added",
        "text": "Language picker in Settings, with French page and Blinky tour."
      },
      {
        "tag": "Fixed",
        "text": "IPC queue depths stay right past 50,000 trace events."
      }
    ]
  },
  {
    "version": "0.6.0",
    "date": "2026-10-08",
    "items": [
      {
        "tag": "Added",
        "text": "Tours gallery with many new tours, several per sample, and step links."
      },
      {
        "tag": "Added",
        "text": "Tours run shell commands, check your work, draw diagrams and show live values."
      },
      {
        "tag": "Added",
        "text": "ESP32 and ESP32-C3 boards; Magic Wand, Watchdog and Message Queue Lab samples."
      },
      {
        "tag": "Added",
        "text": "Trace IPC tab shows who holds locks, plus zbus and CPU sleep states."
      },
      {
        "tag": "Added",
        "text": "Simulator and Live board modes, with Debug over the desktop bridge."
      },
      {
        "tag": "Added",
        "text": "Pipe uart1 to a real USB serial port, with Web Serial."
      },
      {
        "tag": "Added",
        "text": "Help button with shortcuts and this changelog; More menu on phones."
      },
      {
        "tag": "Improved",
        "text": "Device dock suggests what to try and leads with the sample's devices."
      },
      {
        "tag": "Changed",
        "text": "Faster guests, half the download; needs Chrome or Edge 137, Firefox 153 or Safari 27."
      },
      {
        "tag": "Fixed",
        "text": "Debug call stacks and breakpoints, ADXL345 scale, and colour contrast."
      }
    ]
  },
  {
    "version": "0.5.0",
    "date": "2026-07-31",
    "items": [
      {
        "tag": "Added",
        "text": "Desktop bridge for real network and Live board tracing."
      },
      {
        "tag": "Added",
        "text": "Settings menu for bridge URL and Bridge network."
      },
      {
        "tag": "Added",
        "text": "Live board home when tracing a physical board."
      },
      {
        "tag": "Changed",
        "text": "Bridge network lives in Settings only."
      },
      {
        "tag": "Improved",
        "text": "Network uplink copy and port-forward recipe."
      }
    ]
  },
  {
    "version": "0.4.0",
    "date": "2026-07-29",
    "items": [
      {
        "tag": "Added",
        "text": "In-browser Bluetooth with Bumble peers you can drive."
      },
      {
        "tag": "Added",
        "text": "Classic A2DP speaker peer with sound on the page."
      },
      {
        "tag": "Added",
        "text": "FAT disk sample with a browser in the dock."
      },
      {
        "tag": "Added",
        "text": "Guided tours that pause the guest and explain it."
      },
      {
        "tag": "Added",
        "text": "Global keyboard shortcuts and ? help dialog."
      },
      {
        "tag": "Added",
        "text": "MCP2515 CAN bus in the device dock."
      },
      {
        "tag": "Improved",
        "text": "Floating panels resize from any edge."
      }
    ]
  },
  {
    "version": "0.3.0",
    "date": "2026-07-26",
    "items": [
      {
        "tag": "Added",
        "text": "Trace panel with timeline, threads, and queues."
      },
      {
        "tag": "Added",
        "text": "Debug with Step, breakpoints, and memory view."
      },
      {
        "tag": "Added",
        "text": "Pause the guest from the page."
      },
      {
        "tag": "Added",
        "text": "Part catalog with datasheet links."
      },
      {
        "tag": "Added",
        "text": "GPIO 7-segment and PT6314 VFD displays."
      },
      {
        "tag": "Added",
        "text": "LP5012 RGB LED and SCT2024 LED bar."
      },
      {
        "tag": "Improved",
        "text": "Flash and EEPROM stats with wear maps."
      }
    ]
  },
  {
    "version": "0.2.0",
    "date": "2026-07-24",
    "items": [
      {
        "tag": "Added",
        "text": "Sensors, GPIO, LEDs, and displays in the device dock."
      },
      {
        "tag": "Added",
        "text": "I²C and SPI bus views with attach/detach and hex dumps."
      },
      {
        "tag": "Added",
        "text": "Ethernet panel with throughput charts and capture."
      },
      {
        "tag": "Added",
        "text": "GNSS, RTC, fuel gauge, DAC, PWM, and stepper rows."
      },
      {
        "tag": "Added",
        "text": "Sample gallery with board and app pickers."
      },
      {
        "tag": "Added",
        "text": "Drop an ELF onto the window to boot a custom image."
      }
    ]
  },
  {
    "version": "0.1.0",
    "date": "2026-07-22",
    "items": [
      {
        "tag": "Added",
        "text": "Initial release. Zephyr running in a browser tab."
      },
      {
        "tag": "Added",
        "text": "Mock backend so the UI runs without an emulator build."
      },
      {
        "tag": "Added",
        "text": "Terminal and board picker to choose what boots."
      }
    ]
  }
]
