/**
 * GENERATED by scripts/gen-changelog.mjs from CHANGELOG.md. Do not edit by
 * hand — edit CHANGELOG.md and re-run the script.
 */

export interface ChangelogItem {
  tag: string
  text: string
}

export interface ChangelogRelease {
  version: string
  date: string | null
  items: ChangelogItem[]
}

export const CHANGELOG: ChangelogRelease[] = [
  {
    "version": "Unreleased",
    "date": null,
    "items": [
      {
        "tag": "Added",
        "text": "Hover a variable in tour code to see its value."
      },
      {
        "tag": "Added",
        "text": "Tours run shell commands, give you tasks, check your work and chain onward."
      },
      {
        "tag": "Added",
        "text": "Tours stop on guest state, show kernel code and open Trace or Debug views."
      },
      {
        "tag": "Added",
        "text": "Tours draw a message queue as a ring, with read and write pointers."
      },
      {
        "tag": "Added",
        "text": "Tours can draw diagrams, like the sensor pipeline map."
      },
      {
        "tag": "Added",
        "text": "Several tours per sample, and links straight to a tour step."
      },
      {
        "tag": "Added",
        "text": "Guided tours get their own gallery section, plus Button, message queue, sensor pipeline, zbus and state machine tours."
      },
      {
        "tag": "Added",
        "text": "Message Queue Lab sample and tour, driven from the shell."
      },
      {
        "tag": "Added",
        "text": "zbus tab in Trace, and CPU sleep states in the Power tab."
      },
      {
        "tag": "Added",
        "text": "Trace IPC shows mutexes, semaphores and condvars, and who holds them."
      },
      {
        "tag": "Added",
        "text": "ESP32-C3 DevKitC board with GPIO, I²C, SPI flash, CAN and sleep."
      },
      {
        "tag": "Added",
        "text": "ESP32 DevKitC board (Xtensa), with blinky, button and a shell."
      },
      {
        "tag": "Added",
        "text": "Watchdog sample on ESP32-C3, Cortex-M3 and RISC-V, with a live countdown."
      },
      {
        "tag": "Added",
        "text": "Magic Wand TinyML sample on Cortex-A53, with replayable gestures and a capture page."
      },
      {
        "tag": "Added",
        "text": "Simulator and Live board modes, with Debug over the desktop bridge."
      },
      {
        "tag": "Added",
        "text": "Help button with keyboard shortcuts and this changelog."
      },
      {
        "tag": "Added",
        "text": "More menu on phones for Parts and Samples."
      },
      {
        "tag": "Improved",
        "text": "Emulator switches coroutines with JSPI, not Asyncify: faster guests, half the download."
      },
      {
        "tag": "Improved",
        "text": "Larger, higher-contrast tour text in both themes."
      },
      {
        "tag": "Improved",
        "text": "Blinky tours: a page tour that chains on, and one through the code."
      },
      {
        "tag": "Improved",
        "text": "Tours open on an intro card listing their stops."
      },
      {
        "tag": "Improved",
        "text": "Tour cards move, resize, and list only relevant threads, one per line."
      },
      {
        "tag": "Improved",
        "text": "Device dock opens folded to the sample's devices, says I²C/SPI, lists only usable parts, and leaves an edge tab when collapsed."
      },
      {
        "tag": "Improved",
        "text": "Dock rows and bus lists say each value once."
      },
      {
        "tag": "Improved",
        "text": "Trace Timeline shows thread priorities and what blocked threads wait on."
      },
      {
        "tag": "Improved",
        "text": "Tour cards sit beside the dock, full height, and outline what they name."
      },
      {
        "tag": "Improved",
        "text": "Trace hides empty tabs and skips untraced net samples."
      },
      {
        "tag": "Changed",
        "text": "Trace's Queues tab is now IPC, with graph filters."
      },
      {
        "tag": "Changed",
        "text": "Needs Chrome or Edge 137, Firefox 153 or Safari 27 (JSPI)."
      },
      {
        "tag": "Changed",
        "text": "Kernel object lists need an image from current Zephyr main."
      },
      {
        "tag": "Changed",
        "text": "Retired the old gateway and probe packages; use the desktop bridge."
      },
      {
        "tag": "Fixed",
        "text": "Resuming from a breakpoint no longer stops on it again."
      },
      {
        "tag": "Fixed",
        "text": "Debug names the right functions and callers, even at a function's start, and Cortex-M breakpoints hit."
      },
      {
        "tag": "Fixed",
        "text": "Debug register tooltips name the current function's arguments."
      },
      {
        "tag": "Fixed",
        "text": "Tour cards keep the stop line in view and name data pointers."
      },
      {
        "tag": "Fixed",
        "text": "Rereading an earlier tour step no longer strands the paused guest."
      },
      {
        "tag": "Fixed",
        "text": "A tour card's X minimises it instead of skipping the stop."
      },
      {
        "tag": "Fixed",
        "text": "An ELF without a devicetree shows the board's buses."
      },
      {
        "tag": "Fixed",
        "text": "Trace queue depth no longer counts hand-offs to waiting threads."
      },
      {
        "tag": "Fixed",
        "text": "Trace Timeline no longer marks a thread blocked for waking another."
      },
      {
        "tag": "Fixed",
        "text": "The guest reads the ADXL345 at its real scale, not four times too high."
      },
      {
        "tag": "Fixed",
        "text": "Cortex-A53 samples boot without an \"xlat tables low\" warning."
      },
      {
        "tag": "Fixed",
        "text": "Trace's IPC graph keeps your zoom as new routes appear."
      },
      {
        "tag": "Fixed",
        "text": "Trace charts are readable in light mode."
      },
      {
        "tag": "Fixed",
        "text": "Thread and object lists no longer pass the last stop off as current."
      },
      {
        "tag": "Fixed",
        "text": "Accent text, buttons and code colours meet contrast minimums."
      }
    ]
  },
  {
    "version": "0.5.0",
    "date": "2026-07-31",
    "items": [
      {
        "tag": "Added",
        "text": "Desktop bridge for real network and Live board tracing."
      },
      {
        "tag": "Added",
        "text": "Settings menu for bridge URL and Bridge network."
      },
      {
        "tag": "Added",
        "text": "Live board home when tracing a physical board."
      },
      {
        "tag": "Changed",
        "text": "Bridge network lives in Settings only."
      },
      {
        "tag": "Improved",
        "text": "Network uplink copy and port-forward recipe."
      }
    ]
  },
  {
    "version": "0.4.0",
    "date": "2026-07-29",
    "items": [
      {
        "tag": "Added",
        "text": "In-browser Bluetooth with Bumble peers you can drive."
      },
      {
        "tag": "Added",
        "text": "Classic A2DP speaker peer with sound on the page."
      },
      {
        "tag": "Added",
        "text": "FAT disk sample with a browser in the dock."
      },
      {
        "tag": "Added",
        "text": "Guided tours that pause the guest and explain it."
      },
      {
        "tag": "Added",
        "text": "Global keyboard shortcuts and ? help dialog."
      },
      {
        "tag": "Added",
        "text": "MCP2515 CAN bus in the device dock."
      },
      {
        "tag": "Improved",
        "text": "Floating panels resize from any edge."
      }
    ]
  },
  {
    "version": "0.3.0",
    "date": "2026-07-26",
    "items": [
      {
        "tag": "Added",
        "text": "Trace panel with timeline, threads, and queues."
      },
      {
        "tag": "Added",
        "text": "Debug with Step, breakpoints, and memory view."
      },
      {
        "tag": "Added",
        "text": "Pause the guest from the page."
      },
      {
        "tag": "Added",
        "text": "Part catalog with datasheet links."
      },
      {
        "tag": "Added",
        "text": "GPIO 7-segment and PT6314 VFD displays."
      },
      {
        "tag": "Added",
        "text": "LP5012 RGB LED and SCT2024 LED bar."
      },
      {
        "tag": "Improved",
        "text": "Flash and EEPROM stats with wear maps."
      }
    ]
  },
  {
    "version": "0.2.0",
    "date": "2026-07-24",
    "items": [
      {
        "tag": "Added",
        "text": "Sensors, GPIO, LEDs, and displays in the device dock."
      },
      {
        "tag": "Added",
        "text": "I²C and SPI bus views with attach/detach and hex dumps."
      },
      {
        "tag": "Added",
        "text": "Ethernet panel with throughput charts and capture."
      },
      {
        "tag": "Added",
        "text": "GNSS, RTC, fuel gauge, DAC, PWM, and stepper rows."
      },
      {
        "tag": "Added",
        "text": "Sample gallery with board and app pickers."
      },
      {
        "tag": "Added",
        "text": "Drop an ELF onto the window to boot a custom image."
      }
    ]
  },
  {
    "version": "0.1.0",
    "date": "2026-07-22",
    "items": [
      {
        "tag": "Added",
        "text": "Initial release. Zephyr running in a browser tab."
      },
      {
        "tag": "Added",
        "text": "Mock backend so the UI runs without an emulator build."
      },
      {
        "tag": "Added",
        "text": "Terminal and board picker to choose what boots."
      }
    ]
  }
]
